version: "3"

services:
  nginx:
    image: nginx:1.23-alpine
    restart: unless-stopped
    ports:
      - "$APP_HTTP_PORT:80"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    networks:
      - gitea

  app:
    image: gitea/gitea:1.17
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=$POSTGRES_DB
      - GITEA__database__USER=$POSTGRES_USER
      - GITEA__database__PASSWD=$POSTGRES_PASSWORD
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "$APP_SSH_PORT:22"
    depends_on:
      - "db"

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - gitea
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  gitea:
  postgres:

networks:
  gitea:
